(function(){
'use strict';
const form=document.getElementById('applicationForm'),steps=[...document.querySelectorAll('.step')],prevBtn=document.getElementById('prevBtn'),nextBtn=document.getElementById('nextBtn'),submitBtn=document.getElementById('submitBtn'),stepLabel=document.getElementById('stepLabel'),progressBar=document.getElementById('progressBar'),progressPercent=document.getElementById('progressPercent'),review=document.getElementById('reviewSummary'),mode=document.getElementById('modeOfEntry'),deFields=document.getElementById('directEntryFields'), STORAGE='isu_application_progress_v1';let current=1;
const faculties=['Administration','Agriculture','Arts','Basic Medical Sciences','Clinical Sciences','Computing Science and Engineering','Dentistry','Education','Environmental Design and Management','Law','Pharmacy','Science','Social Sciences','Technology'];
const faculty=document.getElementById('faculty');faculties.forEach(f=>{const o=document.createElement('option');o.value=f;o.textContent=f;faculty.appendChild(o)});
const subjects=['English Language','Mathematics','','','',''];const grades=['A1','B2','B3','C4','C5','C6','D7','E8','F9'];const body=document.getElementById('subjectsBody');subjects.forEach((s,i)=>{const tr=document.createElement('tr');tr.innerHTML='<td><input name="subject_'+i+'" value="'+s.replaceAll('"','&quot;')+'" '+(i<2?'readonly required':'required')+' aria-label="Subject '+(i+1)+'"></td><td><select name="grade_'+i+'" required aria-label="Grade '+(i+1)+'"><option value="">Select</option>'+grades.map(g=>'<option>'+g+'</option>').join('')+'</select></td>';body.appendChild(tr)});
function allFields(){return [...form.querySelectorAll('input,select,textarea')].filter(el=>el.type!=='file'&&el.name&&el.name!=='declaration')}
function save(){const data={};allFields().forEach(el=>{if(el.type==='checkbox')data[el.name]=el.checked;else data[el.name]=el.value});try{localStorage.setItem(STORAGE,JSON.stringify(data))}catch(e){}}
function restore(){try{const data=JSON.parse(localStorage.getItem(STORAGE)||'{}');Object.entries(data).forEach(([n,v])=>{const el=form.elements[n];if(!el)return;if(el.type==='checkbox')el.checked=!!v;else el.value=v});updateDE()}catch(e){}}
function updateDE(){const on=mode.value==='Direct Entry';deFields.hidden=!on;deFields.querySelectorAll('[data-de-required]').forEach(el=>el.required=on)}
function markInvalid(el){el.classList.add('invalid');el.addEventListener('input',()=>el.classList.remove('invalid'),{once:true});el.addEventListener('change',()=>el.classList.remove('invalid'),{once:true})}
function validateStep(n){let ok=true;const section=steps[n-1];section.querySelectorAll('input,select,textarea').forEach(el=>{if(el.disabled||el.type==='file'&&n!==4)return;if(el.required&&!el.checkValidity()){markInvalid(el);ok=false}});if(n===2){const score=Number(form.elements.utme_score.value);if(!Number.isFinite(score)||score<0||score>400){markInvalid(form.elements.utme_score);ok=false}}if(n===4&&!validateFiles())ok=false;if(!ok){const first=section.querySelector('.invalid');if(first)first.focus()}return ok}
function bytes(file){return file?file.size:0}
const fileRules={passport:{max:102400,types:['image/jpeg','image/png']},olevel_result:{max:5242880,types:['application/pdf','image/jpeg','image/png']},birth_certificate:{max:5242880,types:['application/pdf','image/jpeg','image/png']},jamb_result:{max:5242880,types:['application/pdf','image/jpeg','image/png']}};
function validateFiles(){let ok=true;Object.entries(fileRules).forEach(([name,r])=>{const el=form.elements[name];const f=el&&el.files[0];if(!f){if(el.required){markInvalid(el);ok=false}return}if(bytes(f)>r.max||!r.types.includes(f.type)){markInvalid(el);ok=false;const info=el.closest('.upload-card')?.querySelector('.file-info');if(info)info.textContent='Invalid file type or size.'}});return ok}
function fileInfo(el){const f=el.files[0],info=el.closest('.upload-card')?.querySelector('.file-info');if(info&&f)info.textContent=f.name+' — '+(f.size/1024).toFixed(1)+' KB'}
Object.keys(fileRules).forEach(name=>{const el=form.elements[name];el.addEventListener('change',()=>{fileInfo(el);validateFiles()})});form.elements.passport.addEventListener('change',()=>{const f=form.elements.passport.files[0],box=document.getElementById('passportPreview');if(!f){box.textContent='Live preview';return}if(fileRules.passport.types.includes(f.type)&&f.size<=fileRules.passport.max){const reader=new FileReader();reader.onload=e=>{box.innerHTML='<img src="'+e.target.result+'" alt="Passport preview">'};reader.readAsDataURL(f)}});
function setStep(n){current=Math.max(1,Math.min(5,n));steps.forEach((s,i)=>s.classList.toggle('active',i===current-1));const pct=current*20;stepLabel.textContent='Step '+current+' of 5';progressPercent.textContent=pct+'%';progressBar.style.width=pct+'%';prevBtn.hidden=current===1;nextBtn.hidden=current===5;submitBtn.hidden=current!==5;if(current===5)buildReview();window.scrollTo({top:0,behavior:'smooth'});save()}
function val(name){return form.elements[name]?.value||'—'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function buildReview(){const rows=(pairs)=>pairs.map(p=>'<div class="review-row"><span>'+esc(p[0])+'</span><strong>'+esc(p[1])+'</strong></div>').join('');const subjects=subjectsFromForm();review.innerHTML='<div class="review-group"><h4>Personal Information</h4>'+rows([['Name',val('surname')+' '+val('first_name')+' '+val('other_names')],['Gender',val('gender')],['Date of Birth',val('date_of_birth')],['Nationality',val('nationality')],['State/LGA',val('state_of_origin')+' / '+val('lga')],['Phone',val('phone')],['Email',val('email')],['Address',val('permanent_address')],['Next of Kin',val('next_of_kin_name')+' / '+val('next_of_kin_phone')]])+'</div><div class="review-group"><h4>JAMB &amp; Programme</h4>'+rows([['JAMB Reg. No.',val('jamb_reg_no')],['UTME Score',val('utme_score')],['Mode',val('mode_of_entry')],['Faculty',val('preferred_faculty')],['Course',val('preferred_course')]])+'</div><div class="review-group"><h4>Academic Background</h4>'+rows([['O\'Level',val('olevel_type')],['Sittings',val('sittings')],['Subjects',subjects]])+'</div><div class="review-group"><h4>Documents</h4>'+rows([['Passport',form.elements.passport.files[0]?.name||'Not selected'],['O\'Level Result',form.elements.olevel_result.files[0]?.name||'Not selected'],['Birth/Age Declaration',form.elements.birth_certificate.files[0]?.name||'Not selected'],['JAMB Result Slip',form.elements.jamb_result.files[0]?.name||'Not selected']])+'</div>'}
function subjectsFromForm(){let out=[];for(let i=0;i<6;i++){const s=val('subject_'+i),g=val('grade_'+i);if(s)out.push(s+' — '+g)}return out.join(', ')}
mode.addEventListener('change',()=>{updateDE();save()});form.addEventListener('input',save);form.addEventListener('change',save);nextBtn.addEventListener('click',()=>{if(validateStep(current))setStep(current+1)});prevBtn.addEventListener('click',()=>setStep(current-1));
form.addEventListener('submit',async e=>{e.preventDefault();document.getElementById('submitError').textContent='';if(!validateStep(5)||!validateStep(4)||!validateStep(3)||!validateStep(2)||!validateStep(1)){const bad=steps.findIndex(s=>s.querySelector('.invalid'));if(bad>=0)setStep(bad+1);return}if(!document.getElementById('declaration').checked){document.getElementById('submitError').textContent='Please accept the declaration before submitting.';return}submitBtn.disabled=true;submitBtn.querySelector('.spinner').style.display='inline-block';try{const fd=new FormData(form);const response=await fetch('process.php',{method:'POST',body:fd,headers:{'Accept':'application/json'}});const result=await response.json();if(!response.ok||!result.success)throw new Error(result.message||'Submission failed.');localStorage.removeItem(STORAGE);window.location.href='success.html?ref='+encodeURIComponent(result.application_id)}catch(err){document.getElementById('submitError').textContent=err.message||'Unable to submit application. Please try again.';submitBtn.disabled=false;submitBtn.querySelector('.spinner').style.display='none'}});
restore();updateDE();setStep(1);
})();
